apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: bchd
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 192.168.2.7:80/zrq/datablau-user:RSV
        ports:
        - containerPort: 11030
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau