apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  namespace: bchd
  labels:
    app: workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow
  template:
    metadata:
      labels:
        app: workflow
    spec:
      containers:
      - name: workflow
        image: 192.168.2.7:80/zrq/datablau-workflow:RSV
        ports:
        - containerPort: 11040
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau