apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataquality
  namespace: bchd
  labels:
    app: dataquality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataquality
  template:
    metadata:
      labels:
        app: dataquality
    spec:
      containers:
      - name: dataquality
        image: 192.168.2.7:80/zrq/datablau-dataquality:RSV
        ports:
        - containerPort: 12030
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau