apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataasset
  namespace: bchd
  labels:
    app: dataasset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataasset
  template:
    metadata:
      labels:
        app: dataasset
    spec:
      containers:
      - name: dataasset
        image: 192.168.2.7:80/zrq/datablau-dataasset:RSV
        ports:
        - containerPort: 14010
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau