apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddm
  namespace: bchd
  labels:
    app: ddm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddm
  template:
    metadata:
      labels:
        app: ddm
    spec:
      containers:
      - name: ddm
        image: 192.168.2.7:80/zrq/datablau-ddm:RSV
        ports:
        - containerPort: 13010
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau