apiVersion: apps/v1
kind: Deployment
metadata:
  name: archy
  namespace: bchd
  labels:
    app: archy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archy
  template:
    metadata:
      labels:
        app: archy
    spec:
      containers:
      - name: archy
        image: 192.168.2.7:80/zrq/datablau-archy:RSV
        ports:
        - containerPort: 13020
          protocol: TCP
        env:
        - name: NACOS_USERNAME
          value: nacos
        - name: NACOS_PASSWD
          value: DataBlau@2022
        - name: NACOS_ADDR
          value: 192.168.7.91:8848
        - name: NACOS_NS
          value: datablau
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: datablau