# 新增 Service 配置（固定端口关键部分）
apiVersion: v1
kind: Service
metadata:
  name: ddm-license-service
  namespace: bchd
spec:
  type: NodePort  # 指定服务类型
  selector:
    app: ddm-license  # 关联 Deployment 的标签
  ports:
    - name: http
      port: 80        # Service 的虚拟端口（集群内访问用）
      targetPort: 18083  # 必须与容器端口一致
      nodePort: 31000    # 固定节点端口（范围 30000-32767）