# 新增 Service 配置（固定端口关键部分）
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bchd
spec:
  type: NodePort  # 服务类型
  selector:
    app: nginx  # 匹配 Deployment 的标签
  ports:
    - name: http
      port: 80          # 集群内访问端口
      targetPort: 18080 # 对应容器的 18080 端口
      nodePort: 31080   # 固定节点端口（范围 30000-32767）